export enum EDefaultApi {
    FIND_ONE_BY_ID = "FIND_ONE_BY_ID",
    FIND_ALL = "FIND_ALL",
    CREATE = "CREATE",
    UPDATE_ONE_BY_ID = "UPDATE",
    BULK_UPDATE = "BULK_UPDATE",
    DELETE_ONE_BY_ID = "DELETE_ONE_BY_ID"
}