export enum ESyntaxRegexPaymentQrSetting {
    ACCOUNT_NUMBER = "ACCOUNT_NUMBER",
    BENEFICIARY_NAME = "BENEFICIARY_NAME",
    TRANSFER_AMOUNT = "TRANSFER_AMOUNT",
    TRANSFER_CONTENT = "TRANSFER_CONTENT"
}